### ISSUE TITLE
I tried to get Cloudtopolis to work for more then 20 times at least

### ISSUE THREAD

**Issue by suntop250ml** [JoelGMSec/Cloudtopolis#4]
I tried to get Cloudtopolis to work for more then 20 times at least, but for some reason I can’t get it to work, here is the steps that I followed:
First I opened this link to get to google cloud shell

https://ssh.cloud.google.com/cloudshell/editor?hl=es&fromcloudshell=true&shellonly=true

and then I ran this command in it: 

curl https://raw.githubusercontent.com/JoelGMSec/Cloudtopolis/master/Cloudtopolis.sh | bash

![P1](https://user-images.githubusercontent.com/59246755/158246690-78a0ae92-220d-4b4d-80ce-8be7e88d14da.jpg)

then I clicked on the link that appeared at the bottom of the shell:

http://localhost:8000

and then I entered the credentials 

![P2](https://user-images.githubusercontent.com/59246755/158246788-3f5ddcd1-bd6b-4b91-aa92-319185f7a086.jpg)

Then I clicked Agents – New Agent

Then I created a new voucher

![P3](https://user-images.githubusercontent.com/59246755/158246863-ad316199-9021-49f7-aa13-134b1f37b901.jpg)

Then I clicked on this link:

https://colab.research.google.com/github/JoelGMSec/Cloudtopolis/blob/master/Cloudtopolis.ipynb

Then I clicked on file – save a copy in drive (because I can’t make changes to this notebook)

Then I copied the voucher name into the requirements section:

![P4](https://user-images.githubusercontent.com/59246755/158246939-8c855bc5-4ed7-4607-8bfd-3a081f06241d.jpg)

Then I clicked on the little arrow (Run cell)

![P5](https://user-images.githubusercontent.com/59246755/158246992-d6ecc93c-d885-46d6-9348-aa6539c66a60.jpg)

Then I clicked on the link that was generated for authorization 

Then I copied that authorization code 

![P6](https://user-images.githubusercontent.com/59246755/158247053-55cff0a9-0354-487a-be3b-1e625123b47e.jpg)

Then this error appear:

![P7](https://user-images.githubusercontent.com/59246755/158247121-88f87d97-1548-4fba-8abf-088f77fe2b01.jpg)

As far as I can tell the error is in this line of code:

!gcloud cloud-shell --quiet ssh -- -p 6000 -o TCPKeepAlive=yes -N -T -C -L 8000:localhost:8000 -4 </dev/null &>/dev/null &

So I tride removing the –quiet option and the null output part and run the code again:

![P8](https://user-images.githubusercontent.com/59246755/158247202-8ebccb8b-3705-499f-b5a3-39275fec58ff.jpg)

And I got this output:

![P9](https://user-images.githubusercontent.com/59246755/158247257-669ae4ef-b7a5-453b-a00e-b694470b08f3.jpg)

I don’t know what is it that am doing wrong ?

Please Help

**Comment by JoelGMSec** [comment]
Hi, 

I just updated the code and it should work fine.
I've been using it with the new changes with no problems, I hope it works for you too :)

Thanks for using my tools,

Regards!

**Comment by suntop250ml** [comment]
Thank you for creating such a great tool, sharing it and keeping it up to date. After the update now it works perfectly.
 
One thing is confusing me though, if I wanted to add another agent using another google account, shouldn’t I change the # [ Connecting with Cloudtopolis Server ] part of the code ? because if run it without changing it then it will not connect to the google account where the server is and how would I change the code to connect to the original server ?

Thank you again for your help

**Comment by JoelGMSec** [comment]
Hi again,

To use another Colab agent simultaneously, what you have to do is to run the notebook with another account (without modifying the code).

Then, when you are asked to authenticate through the Google Cloud SDK (where you get the token that you have to enter in Colab) instead of logging in with the second account, you enter the credentials of the first one.

Here is an example:
Let's say I have two Google accounts, account1@gmail.com and account2@gmail.com.

First we log in to Cloud Shell with account1@gmail.com and we raise Hashtopolis with this account. Then we log in to Colab and run everything with the same account, both the notebook and the Google Cloud SDK login.

Now, we open another Colab notebook in another browser, another tab or private browsing. In this notebook, we log in with account2@gmail.com and run it as usual.

When it asks for the Google Cloud SDK token, we log in with account1@gmail.com (even though the notebook is running account2@gmail.com) and paste the token into the notebook.

In this way, Colab will be able to access the resources of the first account and will be able to communicate with Hashtopolis without any problems.

Finally, if you use Cloudtopolis with friends or colleagues, ideally they should pass you the access link and you should give them back the token (always with the account that is running Hashtopolis) so that they can put it in Colab.

This way, you don't share your passwords with anyone and neither do they :)

In any case, it is not recommended to share these tokens with anyone you don't trust and I am not responsible for what might happen if someone accesses your account with this token.

I hope I have solved your doubts, remember that you can support the project by buying me a coffee or the fabulous swag I have in the shop from darkbyte.net

Regards!
